[workspace]
resolver = "2"
members = ["pong", "ping", "pong-api"]

[workspace.dependencies]
userlib = {git = "https://github.com/cbiffle/exhubris", rev="1f237c0cfbdcd42f6ed5937ea7a93216e40b3b94"}
hubris-task-slots = {git = "https://github.com/cbiffle/exhubris", rev="1f237c0cfbdcd42f6ed5937ea7a93216e40b3b94"}
hubris-notifications = {git = "https://github.com/cbiffle/exhubris", rev="1f237c0cfbdcd42f6ed5937ea7a93216e40b3b94"}
hubris-build = {git = "https://github.com/cbiffle/exhubris", rev="1f237c0cfbdcd42f6ed5937ea7a93216e40b3b94"}
idyll_runtime = {git = "https://github.com/cbiffle/exhubris", rev="1f237c0cfbdcd42f6ed5937ea7a93216e40b3b94"}
drv-stm32g0-sys-api = {git = "https://github.com/cbiffle/exhubris", rev="1f237c0cfbdcd42f6ed5937ea7a93216e40b3b94"}

[profile.release]
debug = true
lto = true
