[workspace]
resolver = "2"
members = ["pong", "ping", "pong-api"]

[workspace.dependencies]
userlib = {git = "https://github.com/cbiffle/exhubris", rev="4338a23d051ed310515fd0e1dbaff060a8f9042b"}
hubris-task-slots = {git = "https://github.com/cbiffle/exhubris", rev="4338a23d051ed310515fd0e1dbaff060a8f9042b"}
hubris-notifications = {git = "https://github.com/cbiffle/exhubris", rev="4338a23d051ed310515fd0e1dbaff060a8f9042b"}
hubris-build = {git = "https://github.com/cbiffle/exhubris", rev="4338a23d051ed310515fd0e1dbaff060a8f9042b"}
idyll_runtime = {git = "https://github.com/cbiffle/exhubris", rev="4338a23d051ed310515fd0e1dbaff060a8f9042b"}
drv-stm32g0-sys-api = {git = "https://github.com/cbiffle/exhubris", rev="4338a23d051ed310515fd0e1dbaff060a8f9042b"}

[profile.release]
debug = true
lto = true
