[workspace]
resolver = "2"
members = ["pong", "ping", "pong-api"]

[workspace.dependencies]
userlib = {git = "https://github.com/cbiffle/exhubris", rev="598e8c500017c3b88b909c300a0fcf32735e213c"}
hubris-task-slots = {git = "https://github.com/cbiffle/exhubris", rev="598e8c500017c3b88b909c300a0fcf32735e213c"}
hubris-notifications = {git = "https://github.com/cbiffle/exhubris", rev="598e8c500017c3b88b909c300a0fcf32735e213c"}
hubris-build = {git = "https://github.com/cbiffle/exhubris", rev="598e8c500017c3b88b909c300a0fcf32735e213c"}
idyll_runtime = {git = "https://github.com/cbiffle/exhubris", rev="598e8c500017c3b88b909c300a0fcf32735e213c"}
drv-stm32g0-sys-api = {git = "https://github.com/cbiffle/exhubris", rev="598e8c500017c3b88b909c300a0fcf32735e213c"}

[profile.release]
debug = true
lto = true
