[workspace]
resolver = "2"
members = ["pong", "ping", "pong-api"]

[workspace.dependencies]
userlib = {git = "https://github.com/cbiffle/exhubris", rev="428880952db8ab275c776a7e8018fa7edbd65358"}
hubris-task-slots = {git = "https://github.com/cbiffle/exhubris", rev="428880952db8ab275c776a7e8018fa7edbd65358"}
hubris-notifications = {git = "https://github.com/cbiffle/exhubris", rev="428880952db8ab275c776a7e8018fa7edbd65358"}
hubris-build = {git = "https://github.com/cbiffle/exhubris", rev="428880952db8ab275c776a7e8018fa7edbd65358"}
idyll_runtime = {git = "https://github.com/cbiffle/exhubris", rev="428880952db8ab275c776a7e8018fa7edbd65358"}
drv-stm32g0-sys-api = {git = "https://github.com/cbiffle/exhubris", rev="428880952db8ab275c776a7e8018fa7edbd65358"}

[profile.release]
debug = true
lto = true
